version: '3'

services:
  api:
    build:
      context: ./Services/API
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8888:8888
    command: uvicorn app:app --host 0.0.0.0 --port 8888

  ocr:
    build:
      context: ./Services/OCR
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 8880:8880
    tty: true
    command: uvicorn app:app --host 0.0.0.0 --port 8880 --log-level debug

  ner:
    build:
      context: ./Services/NER
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 8881:8881
    tty: true
    command: uvicorn app:app --host 0.0.0.0 --port 8881 --log-level debug

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./Services/Mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: nlpadmin
      MONGO_INITDB_ROOT_PASSWORD: nlppass
