version: '3'

services:
  api:
    build:
      context: ./Services/API
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8888:8888
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8888

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./Services/Mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: nlpadmin
      MONGO_INITDB_ROOT_PASSWORD: nlppass
