version: '3'

services:
  api:
    build:
      context: ./Services/API
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8888:8888
    command: uvicorn app:app --host 0.0.0.0 --port 8888

  ocr:
    build:
      context: ./Services/OCR
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 9000:9000
    tty: true
    command: uvicorn app:app --host 0.0.0.0 --port 9000 --log-level debug

  ner:
    build:
      context: ./Services/NER
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 9001:9001
    tty: true
    command: uvicorn app:app --host 0.0.0.0 --port 9001 --log-level debug

  cv:
    build:
      context: ./Services/CV
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 9002:9002
    tty: true
    command: uvicorn app:app --host 0.0.0.0 --port 9002 --log-level debug

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./Services/Mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: nlpadmin
      MONGO_INITDB_ROOT_PASSWORD: nlppass
